# the units of the parameters is m, rad, m/s, m/s^2, g, pixel

#robot ip and port
name: UR10e
ip: 192.168.1.10
port: 30003
FT_ip : 192.168.1.11

#设置孔内径 R 及 轴径 r
R : 0.0252
r : 0.0252

#设置抓取轴时机械臂末端在笛卡尔坐标系下的z值
z : 0.095

#设置装配完成时的z值
z_assembly : 0.0

#的位置->x,y
Bearing_Point:
#  - [ -0.4510, -0.190 ] # y : -196--210 x:445-458
#  - [ -0.5670, -0.190 ]
  - [ -0.7005, -0.187 ]
#  - [ -0.8150, -0.200 ]
#  - [ -0.632, 0.092 ]
  -
#轴的位置->x,y
Shaft_Point:
#  - [ -0.524, 0.346 ]
  - [ -0.624, 0.346 ]
#  - [ -0.724, 0.346 ]

#失败区位置
fail_areas: [-0.63, -0.361]
